#ifndef SETTINGS_H_
#define SETTINGS_H_

#define PRIME_FIELD_BINARY_BIT_LENGTH (131)

#define BRANCHLESS_MODULAR_ADDITION
#define BRANCHLESS_MODULAR_SUBTRACTION
#define BRANCHLESS_MONTGOMERY_MULTIPLICATION

#define MULX
#define AVX2

#endif
