#ifndef SETTINGS_H_
#define SETTINGS_H_

#define PRIME_FIELD_BINARY_BIT_LENGTH (131)

//#define BASE_63_REPRESENTATION
#define BASE_64_REPRESENTATION

#define BRANCHLESS_MODULAR_ADDITION
#define BRANCHLESS_MODULAR_SUBTRACTION
#define BRANCHLESS_MONTGOMERY_MULTIPLICATION

#define VECTORIZED_CODE
#define MULX

#define AVX_ALIGNED_MEMORY

#endif
